apiVersion: maistra.io/v2
kind: ServiceMeshControlPlane
metadata:
  name: istio-system
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  policy:
    type: Istiod
  addons:
    grafana:
      enabled: true
    kiali:
      enabled: true
    prometheus:
      enabled: true
  version: v2.6
  telemetry:
    type: Istiod