apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - patch: |-
      - op: replace
        path: /spec/channel
        value: 'stable-v24'
    target:
      kind: Subscription
      name: rhbk-operator
      namespace: keycloak