apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-keycloak-role
rules:
  - apiGroups: ["k8s.keycloak.org"] # "" indicates the core API group
    resources: ["keycloaks"]
    verbs: ["*"]