apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-gitlab-runner-role
rules:
  - apiGroups: ["apps.gitlab.com"] # "" indicates the core API group
    resources: ["runners"]
    verbs: ["*"]