apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: patch-cluster-wildcard-cert
  annotations:
    argocd.argoproj.io/sync-wave: "3"
rules:
  - apiGroups:
      - operator.openshift.io
    resources:
      - ingresscontrollers
    verbs:
      - get
      - list
      - patch
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: patch-cluster-wildcard-cert
  annotations:
    argocd.argoproj.io/sync-wave: "3"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: patch-cluster-wildcard-cert
subjects:
  - kind: ServiceAccount
    name: cert-manager-wildcard-cert-patch-job-sa
    namespace: cert-manager
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cert-manager-wildcard-cert-patch-job-sa
  namespace: cert-manager
  annotations:
    argocd.argoproj.io/sync-wave: "3"
---
apiVersion: batch/v1
kind: Job
metadata:
  namespace: cert-manager
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  name: cert-manager-wildcard-cert-patch-job
spec:
  template:
    spec:
      containers:
        - image: image-registry.openshift-image-registry.svc:5000/openshift/cli:latest
          command:
            - /bin/bash
            - -c
            - |
              #!/usr/bin/env bash
              if oc get secret router-certs-letsencrypt -n openshift-ingress; then
                oc patch ingresscontroller default -n openshift-ingress-operator --type=merge --patch='{"spec": { "defaultCertificate": { "name": "router-certs-letsencrypt" }}}'
              else
                echo "Could not execute sync as secret 'router-certs-letsencrypt' in namespace 'openshift-ingress' does not exist, check status of CertificationRequest"
                exit 1
              fi
          imagePullPolicy: Always
          name: cert-manager-wildcard-cert-patch-job
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      serviceAccountName: cert-manager-wildcard-cert-patch-job-sa
      terminationGracePeriodSeconds: 30