apiVersion: cloudcredential.openshift.io/v1
kind: CredentialsRequest
metadata:
  name: cert-manager-aws-creds
  namespace: openshift-cloud-credential-operator
spec:
  providerSpec:
    apiVersion: cloudcredential.openshift.io/v1
    kind: AWSProviderSpec
    statementEntries:
      - action:
          - 'route53:*'
        effect: Allow
        resource: '*'
  secretRef:
    name: aws-credentials
    namespace: cert-manager