apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true

resources:
  - certificate.yaml
  - cluster-issuer.yaml
  - credentials-request.yaml
  - cert-manager-dns-patch-job.yaml
  - cert-manager-patch-cluster-wildcard-cert.yaml