apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-setup-cr
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
rules:
  - apiGroups:
      - argoproj.io
    resources:
      - argocds
    verbs:
      - get
      - list
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argocd-setup-rb
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argocd-setup-cr
subjects:
  - kind: ServiceAccount
    name: argocd-setup-sa
    namespace: openshift-gitops
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
  name: argocd-setup-sa