apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-virt-role
rules:
  - apiGroups: ["hco.kubevirt.io"] # "" indicates the core API group
    resources: ["hyperconvergeds"]
    verbs: ["*"]