apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-developer-hub-role
rules:
  - apiGroups: ["rhdh.redhat.com"] # "" indicates the core API group
    resources: ["backstages"]
    verbs: ["*"]
