apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: openshift-gitops
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: Operators/Keycloak/aggregate
    repoURL: 'https://github.com/cmays20/OpenShift-Demo-GitOps.git'
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
