apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: odf-aws-multi-cloud-gateway
  namespace: openshift-gitops
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: Operators/ODF/aggregate/aws-multiCloudGateway
    repoURL: 'https://github.com/cmays20/OpenShift-Demo-GitOps.git'
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
