apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-cert-manager-role
rules:
  - apiGroups: ["cert-manager.io"] # "" indicates the core API group
    resources: ["*"]
    verbs: ["*"]
  - apiGroups: ["cloudcredential.openshift.io"]
    resources: ["credentialsrequests"]
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["serviceaccounts"]
    verbs: ["*"]
  - apiGroups: [ "batch" ]
    resources: [ "jobs" ]
    verbs: [ "*" ]
