apiVersion: v1
kind: Secret
metadata:
  name: config-bundle-secret
  namespace: quay-enterprise
stringData:
  config.yaml: |
    FEATURE_USER_INITIALIZE: true
    BROWSER_API_CALLS_XHR_ONLY: false
    SUPER_USERS:
    - quayadmin
    FEATURE_USER_CREATION: true
    FEATURE_QUOTA_MANAGEMENT: true
    FEATURE_PROXY_CACHE: true
    FEATURE_BUILD_SUPPORT: true
    DEFAULT_SYSTEM_REJECT_QUOTA_BYTES: 102400000
    EXTERNAL_TLS_TERMINATION: true
    FEATURE_UI_V2: true
    AUTHENTICATION_TYPE: OIDC
    RHSSO_LOGIN_CONFIG:
      CLIENT_ID: quay-enterprise
      CLIENT_SECRET: Qn0W8wXcTcjVGDOOpyqW9afDdiy4zxxX
      OIDC_SERVER: https://keycloak.apps.mays-demo.sandbox1367.opentlc.com/realms/quay/
      SERVICE_NAME: Red Hat Keycloak