apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-odf-role
rules:
  - apiGroups: ["odf.openshift.io"] # "" indicates the core API group
    resources: ["*"]
    verbs: ["*"]
  - apiGroups: [ "ocs.openshift.io" ] # "" indicates the core API group
    resources: [ "*" ]
    verbs: [ "*" ]