apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base/

patches:
  - target:
      group: apps.gitlab.com
      version: v1beta1
      kind: GitLab
      name: gitlab
      namespace: gitlab-system
    path: patch-domain.yaml
  - target:
      group: console.openshift.io
      version: v1
      kind: ConsoleLink
      name: gitlab
    path: patch-console-link.yaml