apiVersion: console.openshift.io/v1
kind: ConsoleLink
metadata:
  name: acs-console-link
spec:
  applicationMenu:
    imageURL: 'https://upload.wikimedia.org/wikipedia/commons/3/3a/OpenShift-LogoType.svg'
    section: Red Hat Applications
  href: 'https://someurl'
  location: ApplicationMenu
  text: Red Hat Advanced Cluster Security for Kubernetes