apiVersion: apps.gitlab.com/v1beta1
kind: GitLab
metadata:
  name: gitlab
  namespace: gitlab-system
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  chart:
    values:
      global:
        hosts:
          domain: example.com
        ingress:
          class: none
          configureCertmanager: false
          annotations:
            route.openshift.io/termination: "edge"
      nginx-ingress:
        enabled: false
      certmanager:
        install: false
    version: 7.11.2