apiVersion: apps.gitlab.com/v1beta1
kind: GitLab
metadata:
  name: gitlab
  namespace: gitlab-system
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  chart:
    values:
      gitlab:
        webservice:
          ingress:
            tls:
              secretName: gitlab-tls
        kas:
          ingress:
            tls:
              secretName: kas-tls
        ingress:
          tls:
            secretName: registry-tls
      minio:
        ingress:
          tls:
            secretName: minio-tls
      global:
        hosts:
          domain: example.com
        ingress:
          class: none
          configureCertmanager: false
          annotations:
            route.openshift.io/termination: "edge"
            kubernetes.io/tls-acme: true
            cert-manager.io/cluster-issuer: acme-prod-issuer
      nginx-ingress:
        enabled: false
      certmanager:
        install: false
    version: 7.11.2