apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base/

patches:
  - target:
      group: console.openshift.io
      version: v1
      kind: ConsoleLink
      name: acs-console-link
    patch: |-
      - op: replace
        path: /spec/href
        value: 'https://central-stackrox.apps.mays-demo.sandbox1367.opentlc.com'