apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base/

patches:
  - target:
      group: cert-manager.io
      version: v1
      kind: Certificate
      name: keycloak-certs-letsencrypt
    patch: |-
      - op: replace
        path: /spec/commonName
        value: 'keycloak.apps.mays-demo.sandbox1367.opentlc.com'
      - op: replace
        path: /spec/dnsNames/0
        value: 'keycloak.apps.mays-demo.sandbox1367.opentlc.com'
  - target:
      group: k8s.keycloak.org
      version: v2alpha1
      kind: Keycloak
      name: keycloak
    patch: |-
      - op: replace
        path: /spec/hostname/hostname
        value: 'keycloak.apps.mays-demo.sandbox1367.opentlc.com'
  - target:
      group: console.openshift.io
      version: v1
      kind: ConsoleLink
      name: keycloak
    patch: |-
      - op: replace
        path: /spec/href
        value: 'https://keycloak.apps.mays-demo.sandbox1367.opentlc.com'